version: "3.9"
services:
  zoo_db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
  zoo_service:
    image: zoo_service
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: postgres
    depends_on:
      - zoo_db
